package com.elpais;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.github.dockerjava.transport.DockerHttpClient.Response;

import java.io.OutputStream;
import java.net.HttpURLConnection;
import java.net.URL;
import java.util.*;

import org.asynchttpclient.AsyncHttpClient;
import org.asynchttpclient.BoundRequestBuilder;
import org.asynchttpclient.Dsl;


public class Translator {
    private static final String API_URL = "https://rapid-translate-multi-traduction.p.rapidapi.com/t";
    private static final String API_KEY = "e84d585c5bmshcd461b9da15ffd2p171e69jsn524259845c93"; // Key generated by creating a free subscription in Rapid Translate Multi Traduction

    public String translate(String text) {
        String translatedText = "[Translation Failed]";
        try {
            URL url = new URL("https://rapid-translate-multi-traduction.p.rapidapi.com/t");
            HttpURLConnection conn = (HttpURLConnection) url.openConnection();
            conn.setRequestMethod("POST");
            conn.setRequestProperty("Content-Type", "application/json");
            conn.setRequestProperty("x-rapidapi-key", API_KEY);
            conn.setRequestProperty("x-rapidapi-host", "rapid-translate-multi-traduction.p.rapidapi.com");
            conn.setDoOutput(true);

            String jsonInput = String.format("{\"from\":\"es\",\"to\":\"en\",\"q\":[\"%s\"]}", text.replace("\"", "\\\""));
            try (OutputStream os = conn.getOutputStream()) {
                byte[] input = jsonInput.getBytes("utf-8");
                os.write(input, 0, input.length);
            }

            ObjectMapper mapper = new ObjectMapper();
            JsonNode json = mapper.readTree(conn.getInputStream());

            // If the root is an array, extract the first element
            if (json.isArray() && json.size() > 0) {
                translatedText = json.get(0).asText();
            } else {
                System.out.println("Unexpected JSON structure: " + json.toPrettyString());
            }

        } catch (Exception e) {
            System.out.println("Error during translation: " + e.getMessage());
        }
        return translatedText;
    }
    
}
